### ISSUE TITLE
mg5500 not support by v4.10

### ISSUE THREAD

**Issue by joakim-tjernlund** [tokiclover/bar-overlay#16]
seems like mg5500 is only supported by v4.0 but not v4.1
v4.0 does not build with USE=servicetools.
Would it be possible to combine 4.0 and 4.1 so that USE=="servicetools mg5500" works?

**Comment by tokiclover** [comment]
No combination is possible whatsoever the requirements... *only* using a
specific version with the usb backends with old/new printers is possible --
because of propriatary blobs (libraries) locked to particular models.

Refer to the README file for more info.

Either the printer is supported or neither it is -- no middle ground
when network backend and servicetools involved.

**Comment by joakim-tjernlund** [comment]
What a stupid arrangement by Canon :(
BTW, have you looked at adding an ebuild(or include in current ebuilds) support
for their ScanGear MP SW ?

**Comment by tokiclover** [comment]
This is entirely another issue... Previous version of the ebuilds had
a USE flag for this--scangearamp--because the tarball is similar to the
printer one. So, using a single ebuild could simplify a few things.
However, nobody cared about this and I did not have a printer and
scanner hardware to test this... So, removed everything afterwards.

I even re-wrote everything for the current splited scheme to have the
prnter backends splited with the propriatary blobs... removing the
numerous (previous) release number--rN--so common in the ebuilds found
in bugs.gentoo.org tracker.

If you realy need this, you may either look at the history by using
`git` directly in your local repository: `git log` and then search
`cnijfilter`, notedown the relevent commits (two commits to make a pair)
and then use `git diff COMMIT_{2,1}` to get what you want. Or either by
renaming the relevent ebuilds to scangearamp and use the build system to
get a separate ebuild with minor arrangements.

Good luck.

**Comment by joakim-tjernlund** [comment]
Thanks, I will have a look when I get some free time.
Meanwhile, I have noticed this complaint:
 env-update && source /etc/profile
>>> Regenerating /etc/ld.so.cache...
/sbin/ldconfig: /usr/lib64/libcnbpo426.so is not a symbolic link

/sbin/ldconfig: /usr/lib64/libcnbpcnclui426.so is not a symbolic link

/sbin/ldconfig: /usr/lib64/libcnbpcmcm426.so is not a symbolic link

/sbin/ldconfig: /usr/lib64/libcnbpcnclapi426.so is not a symbolic link

/sbin/ldconfig: /usr/lib64/libcnbpcnclbjcmd426.so is not a symbolic link

/sbin/ldconfig: /usr/lib64/libcnbpess426.so is not a symbolic link

Looks like Canon ships copies of the same lib instead of symlinking ?

**Comment by tokiclover** [comment]
That's false pausitive QA because the objects end with numbers that are
not version numbers of the library objects.

And I've just remembered that you may even found a dedicated ebuild
before it get merged to cnijfilter; so, yoy might just recover one of
those and adapt it to the right versioned tarball.

So, close this issue and open a new one if you want to merge your
changes. You can start with a `git revert` before anything else.

**Comment by joakim-tjernlund** [comment]
I forgot about this until now :( Anyhow these are not false QA positives. Consider:
~ $ ls -l /usr/lib64/libcnbpo426.so*
-rwxr-xr-x 1 root root 48512 Sep 14 21:29 /usr/lib64/libcnbpo426.so*
-rwxr-xr-x 1 root root 48512 Sep 14 21:29 /usr/lib64/libcnbpo426.so.1.0.1*
 ~ $ diff /usr/lib64/libcnbpo426.so /usr/lib64/libcnbpo426.so.1.0.1
 ~ $ 
Standard Unix/Linux prescribes  that libcnbpo426.so should be a symlink to
libcnbpo426.so.1.0.1, not an identical copy.
